// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMbRmNJA3t8L42GUh7tLZ25WjHlUqT2M8',
    appId: '1:140985066323:android:b0f9fcb85589da151bf7a6',
    messagingSenderId: '140985066323',
    projectId: 'advenza-625e6',
    storageBucket: 'advenza-625e6.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHNk8BqTFop8Aq3hGXK6ulLoCC6T4zfow',
    appId: '1:140985066323:web:4bb33e002918ab111bf7a6',
    messagingSenderId: '140985066323',
    projectId: 'advenza-625e6',
    authDomain: 'advenza-625e6.firebaseapp.com',
    storageBucket: 'advenza-625e6.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_gxSt7eKlFejPGPMWAKgCla7tCTKAUbc',
    appId: '1:140985066323:ios:889d4e6947f3be8e1bf7a6',
    messagingSenderId: '140985066323',
    projectId: 'advenza-625e6',
    storageBucket: 'advenza-625e6.appspot.com',
    iosBundleId: 'com.example.advenzaProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_gxSt7eKlFejPGPMWAKgCla7tCTKAUbc',
    appId: '1:140985066323:ios:889d4e6947f3be8e1bf7a6',
    messagingSenderId: '140985066323',
    projectId: 'advenza-625e6',
    storageBucket: 'advenza-625e6.appspot.com',
    iosBundleId: 'com.example.advenzaProject',
  );

}